package lt.pra_va;

public enum AntecedentTypes {
    TIKRINIS_DAIKTAVARDIS,
    AKRONIMAS,
    JAUSTUKAS,
    SUTRUMPINIMAS,
    DAIKTAVARDIS,
    SKAITVARDIS,
    PRIEVEIKSMIS,
    BUDVARDIS,
    VEIKSMAZODIS,
    PRIELINKSNIS,
    DALELYTE,
    JUNGTUKAS,
    ROMENISKAS_SKAICIUS
}
